### ISSUE TITLE
python main.py 出错

### ISSUE THREAD

**Issue by FengJun1206** [iopsgroup/imoocc#15]
python main.py 运行出错：

```python
/home/hj/Projects/imoocc/apps/detail/models.py:7: RemovedInDjango19Warning: Model class apps.detail.models.ConnectionInfo doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class ConnectionInfo(models.Model):

Traceback (most recent call last):
  File "main.py", line 21, in <module>
    from scanhosts.util.nmap_all_server import NmapNet
  File "/home/hj/Projects/imoocc/scanhosts/util/nmap_all_server.py", line 23, in <module>
    from apps.detail.models import ConnectionInfo, VirtualServerInfo, PhysicalServerInfo, NetConnectionInfo, NetWorkInfo
  File "/home/hj/Projects/imoocc/apps/detail/models.py", line 7, in <module>
    class ConnectionInfo(models.Model):
  File "/root/.virtualenvs/imooc/lib/python2.7/site-packages/django/db/models/base.py", line 309, in __new__
    new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
  File "/root/.virtualenvs/imooc/lib/python2.7/site-packages/django/apps/registry.py", line 221, in register_model
    (model_name, app_label, app_models[model_name], model))
RuntimeError: Conflicting 'connectioninfo' models in application 'detail': <class 'detail.models.ConnectionInfo'> and <class 'apps.detail.models.ConnectionInfo'>.
```

**Comment by amsmoking** [comment]
启动项目是运行
python3 manager.py runserver
